### ISSUE TITLE
Check for duplicate imports

### ISSUE THREAD

**Issue by stdavis** [agrc/AmdButler#1]

**Comment by steveoh** [comment]
I just bumped into this. 

It seems like you could:
 1. crawl the existing imports for the file (which you already do for the removal process)
    1. save into a set
 1. crawl the directory for available imports (which you are already doing) 
     1. save into a set
 1. Do a python set subtraction to get the difference 
     1. show the result as the list to the users.

I just glanced at the code but I don't understand it enough for a pull request. :droplet:

**Comment by stdavis** [comment]
I like this idea. The only issue that I can think of is that a user might be confused if a module that he is typing in does not show up in the list. They might think that they are typing it in wrong. I wonder if it should still show up in the list but then display a popup or something that tells them that it's already added.

What do you think?

**Comment by steveoh** [comment]
I think the way package manager works in sublime text is a good example/expected behavior; If you try to install a package you already have it doesn't show up.

**Comment by stdavis** [comment]
Good point.

On Sat, Jan 31, 2015 at 11:59 AM, steveoh <notifications@github.com> wrote:

> I think the way package manager works in sublime text is a good
> example/expected behavior; If you try to install a package you already have
> it doesn't show up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/AmdButler/issues/1#issuecomment-72330859>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@ScottAGRC <https://twitter.com/ScottAGRC>
