### ISSUE TITLE
Add multiple references

### ISSUE THREAD

**Issue by steveoh** [agrc/AmdButler#37]
The quick pane allows you use the right arrow key to open multiple files. I wonder if we could use this same UX to allow you to add multiple amd imports with one command invocation. 

Good talk.

**Comment by stdavis** [comment]
I really like this idea. But I can't figure out a way to make this work with the [existing API](http://www.sublimetext.com/docs/3/api_reference.html). Can't figure out how to listen for key press events on the quick panel. This may have to wait until this project gets ported to an Atom plugin.
