### ISSUE TITLE
AMD Butler commands not accessible in Windows version of Sublime 3

### ISSUE THREAD

**Issue by bchastain** [agrc/AmdButler#42]
No matter what version/build of Sublime Text 3 for Windows I try to install (x86/x64, portable/full, dev/stable/old, etc.), I can't seem to get AMD Butler to work with it (I've tried older versions of AMD Butler as well). After installing Sublime, I install Package Control, and then from Package Control I install AMD Butler and it says it installs successfully, but no AMD Butler commands ever show up in the command palette. I've tried this on multiple Windows 7 machines with the same result.

There are no errors in the console - it just shows these lines on loading:
reloading plugin AMD Butler.__init__
reloading plugin AMD Butler.amdbutler
reloading plugin AMD Butler.buffer_parser
reloading plugin AMD Butler.crawler
reloading plugin AMD Butler.zipper

**Comment by bchastain** [comment]
Do I need to modify anything in Package Settings->AmdButler? Whenever I try to open either the Default or User settings it gives me the following error:
Unable to open /<my sublime data path>/Packages/AmdButler/AmdButler.sublime-settings
Unable to open /<my sublime data path>/Packages/User/AmdButler.sublime-settings

**Comment by steveoh** [comment]
I think you will only see the commands if you have a javascript syntax file open.

**Comment by bchastain** [comment]
Aha, that was it. The commands aren't accessible on javascript inside HTML files. I guess I should make that as a feature request then.

Thanks!
